name: Android CI

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '17'
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew assembleDebug assembleDebugAndroidTest assembleDebugUnitTest
    - name: Run unit tests
      run: ./gradlew testDebugUnitTest
    - name: Grant execute permission for flank_auth.sh
      run: chmod +x flank_auth.sh
    - name: Add auth for flank
      env:
        GCLOUD_KEY: ${{ secrets.GCLOUD_KEY }}
      run: |
        ./flank_auth.sh
    - name: Run UI tests
      run: ./gradlew runFlank
